// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zprbixmapqtzwjxlaijq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpwcmJpeG1hcHF0endqeGxhaWpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MDQ2NDMsImV4cCI6MjA2OTI4MDY0M30.ZhB-_N3odXUqOUM7lHrx-jc6LIh5Sf5az2-N6VMeNrE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});